const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday'];
const SLOTS=[['08:00','08:50'],['08:50','09:40'],['09:40','10:30'],['10:30','11:20'],['11:20','12:10'],['12:10','13:00'],['13:00','13:50'],['13:50','14:40'],['14:40','15:30'],['15:30','16:20'],['16:20','17:10']];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), time=i=>SLOTS[i]?`${SLOTS[i][0]}–${SLOTS[i][1]}`:'', uid=()=>crypto.randomUUID();
let sb=null,user=null,state={faculty:[],programs:[],semesters:[],sections:[],rooms:[],labs:[],courses:[],assignments:[],prefs:[],versions:[],entries:[],audit:[],settings:{}};
let currentVersion=null, currentView='dashboard', currentFilter={};

async function config(){const r=await fetch('/.netlify/functions/config');if(!r.ok)throw Error('Netlify configuration endpoint unavailable');return r.json()}
async function init(){try{const c=await config();if(!c.supabaseUrl||!c.supabaseAnonKey)throw Error('Supabase is not configured. Add SUPABASE_URL and SUPABASE_ANON_KEY in Netlify.');sb=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey);const {data}=await sb.auth.getSession();if(data.session)await start(data.session.user);else showAuth();sb.auth.onAuthStateChange(async(_e,s)=>{if(s)await start(s.user);else showAuth()})}catch(e){$('#loading').textContent=e.message;}}
function showAuth(){ $('#loading').classList.add('hidden');$('#app').classList.add('hidden');$('#auth').classList.remove('hidden') }
async function start(u){user=u;$('#auth').classList.add('hidden');$('#loading').classList.remove('hidden');try{await ensureSeed();await load();$('#loading').classList.add('hidden');$('#app').classList.remove('hidden');bind();renderAll()}catch(e){$('#loading').textContent=`Setup error: ${e.message}`}}
async function ensureSeed(){
 const {data:f}=await sb.from('faculty').select('id,name');
 if((f||[]).length<10){const rows=[['Dr. Fareed Ahmad','DSCS',10],['Mr. Muhammad Zafar Iqbal Karmani','DSCS',17],['Mr. Anees Ahmad Zafar','DSCS',12],['Mr. Ali Raza Aslam','DSCS',18],['Ms. Hafsa Mehboob','DSCS',15],['Ms. Sofia','DSCS',15],['Mr. Shahid','Visiting',11],['Ms. Asia','Visiting',6],['Ms. Tahira','Visiting',9],['Mr. Abdullah','Visiting',4]].map(x=>({name:x[0],faculty_type:x[1],allocated_credit_hours:x[2],max_weekly_slots:20}));await sb.from('faculty').upsert(rows,{onConflict:'name'});}
 const {data:p}=await sb.from('programs').select('id,name');const pm=new Map((p||[]).map(x=>[x.name,x.id]));for(const n of ['BS Computer Science','BS BioTec','BS Zoology','MLT','Food Science','Poultry'])if(!pm.has(n)){const {data:x}=await sb.from('programs').insert({name:n}).select().single();if(x)pm.set(n,x.id)}
 const {data:sem}=await sb.from('semesters').select('id,name,program_id');const sm=new Map((sem||[]).map(x=>[`${x.program_id}|${x.name}`,x.id]));for(const n of ['I','III','V']){const k=`${pm.get('BS Computer Science')}|${n}`;if(!sm.has(k)){const {data:x}=await sb.from('semesters').insert({program_id:pm.get('BS Computer Science'),name:n,sort_order:+n}).select().single();if(x)sm.set(k,x.id)}}
 const sectionNames={'I':['Morning','Evening A','Evening B'],'III':['Morning','Evening'],'V':['Morning A','Morning B','Evening']};for(const n of Object.keys(sectionNames))for(const s of sectionNames[n])await sb.from('sections').upsert({program_id:pm.get('BS Computer Science'),semester_id:sm.get(`${pm.get('BS Computer Science')}|${n}`),name:s},{onConflict:'program_id,semester_id,name'});
 const courses=[['PF-I','Programming Fundamentals','I',3,3,0],['AICT-I','Applications of ICT','I',3,3,0],['DS-I','Discrete Structures','I',3,3,0],['CAL-I','Calculus and Analytic Geometry','I',3,3,0],['ENG-I','Functional English','I',3,3,0],['SS-I','Social Science I','I',2,2,0],['DS-III','Data Structures','III',3,3,0],['AI-III','Artificial Intelligence','III',3,3,0],['CN-III','Computer Networks','III',3,3,0],['SE-III','Software Engineering','III',3,3,0],['PHY-III','Applied Physics','III',3,3,0],['MVC-III','Multivariable Calculus','III',3,3,0],['OS-V','Operating Systems','V',3,3,0],['HCI-V','HCI & Computer Graphics','V',3,3,0],['CA-V','Computer Architecture','V',3,3,0],['ML-V','Machine Learning','V',3,3,0],['WEB-V','Web Technologies','V',3,3,0],['MGT-V','Introduction to Management','V',3,3,0]];
 const {data:existing}=await sb.from('courses').select('id,course_code');const em=new Set((existing||[]).map(x=>x.course_code));const inserts=courses.filter(x=>!em.has(x[0])).map(x=>({course_code:x[0],course_title:x[1],program_id:pm.get('BS Computer Science'),semester_id:sm.get(`${pm.get('BS Computer Science')}|${x[2]}`),credit_hours:x[3],theory_hours:x[4],lab_hours:x[5],theory_duration_slots:1}));if(inserts.length)await sb.from('courses').insert(inserts);
 const {data:allc}=await sb.from('courses').select('id,course_code');const fm=new Map((f||[]).map(x=>[x.name,x.id]));const eligible={'PF-I':['Dr. Fareed Ahmad','Mr. Shahid'],'AICT-I':['Mr. Anees Ahmad Zafar','Ms. Sofia','Mr. Shahid','Ms. Tahira'],'DS-I':['Mr. Ali Raza Aslam'],'DS-III':['Mr. Muhammad Zafar Iqbal Karmani'],'CN-III':['Ms. Sofia'],'SE-III':['Ms. Hafsa Mehboob'],'PHY-III':['Ms. Asia'],'OS-V':['Mr. Ali Raza Aslam'],'HCI-V':['Ms. Hafsa Mehboob'],'CA-V':['Mr. Muhammad Zafar Iqbal Karmani'],'ML-V':['Dr. Fareed Ahmad','Ms. Tahira'],'WEB-V':['Mr. Anees Ahmad Zafar'],'AI-III':[],'CAL-I':[],'ENG-I':[],'SS-I':[],'MVC-III':[],'MGT-V':['Mr. Abdullah']};const cm=new Map((allc||[]).map(x=>[x.course_code,x.id]));for(const [code,names] of Object.entries(eligible)){for(const n of names)if(fm.has(n))await sb.from('course_teacher_assignments').upsert({course_id:cm.get(code),faculty_id:fm.get(n)},{onConflict:'course_id,faculty_id'});}
 const {data:r}=await sb.from('rooms').select('name');if((r||[]).length<4)await sb.from('rooms').upsert(['Room 1','Room 2','Marketing Room','Conference Room'].map(name=>({name,capacity:30})),{onConflict:'name'});const {data:l}=await sb.from('labs').select('name');if((l||[]).length<2)await sb.from('labs').upsert(['Lab 1','Lab 2'].map(name=>({name,capacity:30})),{onConflict:'name'});
}
async function load(){const qs=['faculty','programs','semesters','sections','rooms','labs','courses','course_teacher_assignments','faculty_preferences','timetable_versions','timetable_entries','audit_log'];for(const t of qs){const {data,error}=await sb.from(t).select('*');if(error)throw error;state[t==='course_teacher_assignments'?'assignments':t==='faculty_preferences'?'prefs':t==='timetable_versions'?'versions':t==='timetable_entries'?'entries':t==='audit_log'?'audit':t]=data||[]}const s=state.settings;const {data:set}=await sb.from('system_settings').select('key,value');for(const x of set||[])s[x.key]=x.value;currentVersion=state.versions.find(v=>v.status==='draft'&&!v.locked)||state.versions[0];if(!currentVersion){const {data:v,error}=await sb.from('timetable_versions').insert({name:'Draft 1',academic_session:'2026-27',created_by:user.id}).select().single();if(error)throw error;currentVersion=v;state.versions=[v]}}
function role(){return stateProfile?.role||'teacher'}let stateProfile=null;
async function getProfile(){const {data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();stateProfile=data||{role:'teacher'};}
async function audit(action,type,id,prev,next){await sb.from('audit_log').insert({actor_id:user.id,action,entity_type:type,entity_id:id||null,previous_value:prev||null,new_value:next||null})}
function rowsForEntries(){return state.entries.filter(e=>e.version_id===currentVersion?.id)}
function overlaps(a,b){return a.day===b.day&&a.start_slot< b.start_slot+b.duration_slots&&b.start_slot<a.start_slot+a.duration_slots}
function hardIssues(candidate,list=rowsForEntries()){const out=[];if(!DAYS.includes(candidate.day))out.push('Invalid working day.');if(candidate.start_slot<0||candidate.start_slot+candidate.duration_slots>SLOTS.length)out.push('Session exceeds the final daily period.');if(candidate.session_type==='Theory'&&!([1,2].includes(+candidate.duration_slots)))out.push('Theory must occupy 1 or 2 consecutive slots.');if(candidate.session_type==='Lab'&&+candidate.duration_slots!==3)out.push('Every lab must occupy exactly 3 consecutive slots.');if(candidate.session_type==='Lab'&&(!candidate.lab_id||candidate.room_id))out.push('Lab sessions require a lab and no theory room.');if(candidate.session_type==='Theory'&&(!candidate.room_id||candidate.lab_id))out.push('Theory sessions require a classroom and no lab.');for(const e of list){if(e.id===candidate.id||!overlaps(candidate,e))continue;if(e.faculty_id===candidate.faculty_id)out.push(`Teacher conflict: ${name('faculty',e.faculty_id)} already teaches ${name('courses',e.course_id)} on ${e.day} ${time(e.start_slot)}.`);if(e.section_id===candidate.section_id)out.push(`Section conflict: ${name('sections',e.section_id)} already has ${name('courses',e.course_id)} on ${e.day} ${time(e.start_slot)}.`);if(candidate.room_id&&e.room_id===candidate.room_id)out.push(`Room conflict: ${name('rooms',e.room_id)} is occupied on ${e.day} ${time(e.start_slot)}.`);if(candidate.lab_id&&e.lab_id===candidate.lab_id)out.push(`Lab conflict: ${name('labs',e.lab_id)} is occupied on ${e.day} ${time(e.start_slot)}.`)}for(const p of state.prefs.filter(x=>x.faculty_id===candidate.faculty_id&&x.day===candidate.day&&x.kind==='unavailable'))for(let s=candidate.start_slot;s<candidate.start_slot+candidate.duration_slots;s++)if(+p.slot===s)out.push(`Teacher unavailable: ${name('faculty',candidate.faculty_id)} is unavailable ${candidate.day} ${time(s)}.`);return [...new Set(out)]}
function alternatives(candidate){const a=[];for(const d of DAYS)for(let s=0;s<=SLOTS.length-candidate.duration_slots;s++){const c={...candidate,day:d,start_slot:s};if(!hardIssues(c).length){a.push(`${d} ${time(s)}`);if(a.length>=5)return a}}return a}
function name(t,id){return state[t]?.find(x=>x.id===id)?.name||state[t]?.find(x=>x.id===id)?.course_title||id||''}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('#loginForm').onsubmit=login;$('#logoutBtn').onclick=()=>sb.auth.signOut();$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');$('#generateBtn').onclick=generate;$('#generateBtn2').onclick=generate;$('#addBtn').onclick=openSchedule;$('#openSchedule').onclick=openSchedule;$('#validateBtn').onclick=validate;$('#printBtn').onclick=()=>printView('complete');$('#printBtn2').onclick=()=>printView('complete');$('#aiBtn').onclick=()=>$('#aiDialog').showModal();$('#aiSend').onclick=ai;$('#saveSchedule').onclick=saveSchedule;$('#addFaculty').onclick=addFaculty;$('#addCourse').onclick=addCourse;$('#addSection').onclick=addSection;$('#addResource').onclick=addResource;$('#prefFaculty').onchange=renderPrefs;$('#saveSettings').onclick=saveSettings;$('#versionBtn').onclick=newVersion;$('#reportCsv').onclick=exportCSV;$('#importBtn').onclick=()=>$('#fileInput').click();$('#importBtn2').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>e.target.files[0]&&importCSV(e.target.files[0]);document.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>printView(b.dataset.print));}
async function login(e){e.preventDefault();$('#authMsg').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)$('#authMsg').textContent=error.message}
function view(v){currentView=v;document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('#'+v)?.classList.remove('hidden');renderAll()}
function renderAll(){renderDashboard();renderFaculty();renderCourses();renderAcademic();renderResources();renderPrefs();renderManual();renderTable();renderReports();renderAudit();renderSettings()}
function renderDashboard(){const es=rowsForEntries(),bad=es.flatMap(e=>hardIssues(e,es.filter(x=>x.id!==e.id)));$('#teacherCount').textContent=state.faculty.length;$('#courseCount').textContent=state.courses.length;$('#sectionCount').textContent=state.sections.length;$('#allocationCount').textContent=es.length;$('#conflictCount').textContent=bad.length;$('#unscheduledCount').textContent=state.unscheduled?.length||0;$('#status').textContent=bad.length?'Hard-rule conflicts require correction.':'All saved entries pass the deterministic engine.'}
function renderFaculty(){const w={};for(const e of rowsForEntries())w[e.faculty_id]=(w[e.faculty_id]||0)+e.duration_slots;$('#facultyContent').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Faculty</th><th>Type</th><th>Courses</th><th>Allocated CH</th><th>Scheduled slots</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.faculty.map(f=>{const cs=state.assignments.filter(a=>a.faculty_id===f.id).map(a=>name('courses',a.course_id));return `<tr><td>${esc(f.name)}</td><td>${esc(f.faculty_type)}</td><td>${esc([...new Set(cs)].join(', '))}</td><td>${f.allocated_credit_hours}</td><td>${w[f.id]||0}/${f.max_weekly_slots}</td><td>${(w[f.id]||0)>f.max_weekly_slots?'Overload':'OK'}</td><td><button class="mini" onclick="window.editFaculty('${f.id}')">Edit</button></td></tr>`}).join('')}</tbody></table></div>`}
function renderCourses(){const q=state.courses;$('#coursesContent').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Code</th><th>Course</th><th>Program</th><th>Semester</th><th>CH</th><th>Theory</th><th>Lab</th><th>Eligible Faculty</th><th>Action</th></tr></thead><tbody>${q.map(c=>`<tr><td>${esc(c.course_code)}</td><td>${esc(c.course_title)}</td><td>${esc(state.programs.find(p=>p.id===c.program_id)?.name||'')}</td><td>${esc(state.semesters.find(s=>s.id===c.semester_id)?.name||'')}</td><td>${c.credit_hours}</td><td>${c.theory_hours}</td><td>${c.lab_hours}</td><td>${esc(state.assignments.filter(a=>a.course_id===c.id).map(a=>name('faculty',a.faculty_id)).join(', '))}</td><td><button class="mini" onclick="window.editCourse('${c.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div><p><small>Use the CSV template: course_code,course_title,program,semester,credit_hours,theory_hours,lab_hours,teacher.</small></p>`}
function renderAcademic(){const groups=state.sections.map(s=>{const p=state.programs.find(x=>x.id===s.program_id)?.name||'';const se=state.semesters.find(x=>x.id===s.semester_id)?.name||'';return `<tr><td>${esc(p)}</td><td>${esc(se)}</td><td>${esc(s.name)}</td><td><button class="mini" onclick="window.del('sections','${s.id}')">Delete</button></td></tr>`}).join('');$('#academicContent').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Program</th><th>Semester</th><th>Section</th><th>Action</th></tr></thead><tbody>${groups}</tbody></table></div>`}
function renderResources(){const rr=state.rooms.map(r=>`<tr><td>${esc(r.name)}</td><td>Theory</td><td>${r.capacity}</td><td><button class="mini" onclick="window.del('rooms','${r.id}')">Delete</button></td></tr>`).join('')+state.labs.map(r=>`<tr><td>${esc(r.name)}</td><td>Lab</td><td>${r.capacity}</td><td><button class="mini" onclick="window.del('labs','${r.id}')">Delete</button></td></tr>`).join('');$('#resourcesContent').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Capacity</th><th>Action</th></tr></thead><tbody>${rr}</tbody></table></div>`}
function renderPrefs(){const s=$('#prefFaculty');if(!s)return;s.innerHTML=state.faculty.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');renderPrefsGrid()}
function renderPrefsGrid(){const id=$('#prefFaculty').value||state.faculty[0]?.id;if(!id)return;$('#prefGrid').innerHTML=`<div class="pref-grid">${DAYS.map(d=>`<div><h4>${d}</h4>${SLOTS.map((_,i)=>{const p=state.prefs.find(x=>x.faculty_id===id&&x.day===d&&+x.slot===i);return `<button class="pref ${p?.kind||'none'}" onclick="window.setPref('${id}','${d}',${i})">${time(i)}<br>${p?.kind||'available'}</button>`}).join('')}</div>`).join('')}</div><p><small>Click cycles Available → Preferred → Unavailable → Available.</small></p>`}
function renderManual(){if($('#manualContent'))$('#manualContent').innerHTML=`<div class="panel"><b>Current version:</b> ${esc(currentVersion?.name||'Draft')} · ${esc(currentVersion?.status||'draft')} ${currentVersion?.locked?'· LOCKED':''}<p>Use New Allocation to schedule a validated session.</p></div>`}
function renderTable(){const es=rowsForEntries();$('#table tbody').innerHTML=es.map(e=>`<tr><td>${e.day}</td><td>${time(e.start_slot)}${e.duration_slots>1?` · ${e.duration_slots} slots`:''}</td><td>${esc(name('courses',e.course_id))}</td><td>${esc(name('faculty',e.faculty_id))}</td><td>${esc(name('sections',e.section_id))}</td><td>${e.room_id?esc(name('rooms',e.room_id)):esc(name('labs',e.lab_id))}</td><td>${e.session_type}</td><td><button class="mini" onclick="window.toggleLock('${e.id}')">${e.locked?'Unlock':'Lock'}</button></td><td><button class="mini" onclick="window.editEntry('${e.id}')">Edit</button> <button class="mini danger" onclick="window.delEntry('${e.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="9">No scheduled sessions.</td></tr>';const bad=es.flatMap(e=>hardIssues(e,es.filter(x=>x.id!==e.id)));$('#conflictBox').innerHTML=bad.length?`<div class="alert"><b>${bad.length} hard-rule issue(s)</b><ul>${bad.slice(0,12).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'<div class="success">✓ All timetable entries pass hard constraints.</div>'}
function renderReports(){const es=rowsForEntries();const work={};es.forEach(e=>work[e.faculty_id]=(work[e.faculty_id]||0)+e.duration_slots);$('#reportsContent').innerHTML=`<div class="grid2"><section class="panel"><h2>Teacher workload</h2>${state.faculty.map(f=>`<p><b>${esc(f.name)}</b> · ${work[f.id]||0}/${f.max_weekly_slots} slots · ${(work[f.id]||0)>f.max_weekly_slots?'OVERLOAD':'OK'}</p>`).join('')}</section><section class="panel"><h2>Versions</h2>${state.versions.map(v=>`<p>${esc(v.name)} · ${v.status} ${v.locked?'· locked':''}</p>`).join('')}</section></div>`}
function renderAudit(){$('#auditContent').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>New Value</th></tr></thead><tbody>${state.audit.slice().reverse().slice(0,100).map(a=>`<tr><td>${new Date(a.created_at).toLocaleString()}</td><td>${esc(a.action)}</td><td>${esc(a.entity_type)}</td><td><code>${esc(JSON.stringify(a.new_value||{}))}</code></td></tr>`).join('')}</tbody></table></div>`}
function renderSettings(){const x=state.settings.scheduler||{};$('#academicSession').value=currentVersion?.academic_session||'2026-27';$('#maxConsecutive').value=x.max_consecutive_theory||3;$('#maxDaily').value=x.max_classes_per_day||5;$('#sameRoom').checked=x.prefer_same_room!==false;$('#allowOverload').checked=x.allow_overload===true}
function renderValidation(c){const issues=hardIssues(c);$('#scheduleValidation').innerHTML=issues.length?`<div class="alert"><b>Cannot save</b><ul>${issues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p><b>Alternatives:</b> ${alternatives(c).join(' · ')||'None found'}</p></div>`:'<div class="success">✓ Valid allocation</div>';return !issues.length}
function fillSchedule(a={}){const f=$('#scheduleForm');f.elements.id.value=a.id||'';f.elements.section_id.innerHTML=state.sections.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');f.elements.course_id.innerHTML=state.courses.map(x=>`<option value="${x.id}">${esc(x.course_code+' · '+x.course_title)}</option>`).join('');f.elements.faculty_id.innerHTML=state.faculty.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');f.elements.start_slot.innerHTML=SLOTS.map((_,i)=>`<option value="${i}">${time(i)}</option>`).join('');f.elements.room_id.innerHTML='<option value="">Select classroom</option>'+state.rooms.filter(x=>x.active).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');f.elements.lab_id.innerHTML='<option value="">Select lab</option>'+state.labs.filter(x=>x.active).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');Object.entries(a).forEach(([k,v])=>f.elements[k]&&(f.elements[k].value=v));f.elements.session_type.onchange=()=>{const lab=f.elements.session_type.value==='Lab';f.elements.duration_slots.value=lab?'3':'1';f.elements.duration_slots.disabled=lab;f.elements.room_id.disabled=lab;f.elements.lab_id.disabled=!lab;};f.elements.section_id.onchange=f.elements.course_id.onchange=f.elements.faculty_id.onchange=f.elements.day.onchange=f.elements.start_slot.onchange=f.elements.duration_slots.onchange=()=>renderValidation(formObject());f.elements.session_type.onchange();renderValidation(formObject())}
function formObject(){const f=$('#scheduleForm');const o=Object.fromEntries(new FormData(f));o.start_slot=+o.start_slot;o.duration_slots=o.session_type==='Lab'?3:+o.duration_slots;o.room_id=o.room_id||null;o.lab_id=o.lab_id||null;return o}
function openSchedule(){fillSchedule();$('#scheduleDialog').showModal()}
window.editEntry=id=>{const e=state.entries.find(x=>x.id===id);if(e){fillSchedule(e);$('#scheduleDialog').showModal()}}
async function saveSchedule(e){e.preventDefault();const c=formObject();if(!renderValidation(c))return;const old=state.entries.find(x=>x.id===c.id);if(old?.locked||currentVersion.locked)return alert('This timetable entry/version is locked.');c.version_id=currentVersion.id;delete c.id;let result;if(old){result=await sb.from('timetable_entries').update(c).eq('id',old.id)}else result=await sb.from('timetable_entries').insert(c);if(result.error){alert(result.error.message);return}await audit(old?'update':'create','timetable_entry',old?.id,c);$('#scheduleDialog').close();await load();renderAll()}
async function validate(){const es=rowsForEntries();const bad=es.flatMap(e=>hardIssues(e,es.filter(x=>x.id!==e.id)));alert(bad.length?bad.slice(0,10).join('\n'):'Timetable is conflict-free.')}
async function generate(){if(!currentVersion||currentVersion.locked)return alert('Create or unlock a draft version first.');const base=rowsForEntries().filter(e=>e.locked);const jobs=[];for(const c of state.courses.filter(x=>x.active)){const sec=state.sections.filter(s=>s.semester_id===c.semester_id&&s.active);const assigned=state.assignments.filter(a=>a.course_id===c.id);const facultyIds=assigned.map(a=>a.faculty_id);for(const s of sec)for(let i=0;i<Math.max(1,Math.round(c.theory_hours||c.credit_hours));i++)jobs.push({course:c,section:s,facultyIds,duration:c.lab_hours>0?3:c.theory_duration_slots||1,type:c.lab_hours>0?'Lab':'Theory'})}
 jobs.sort((a,b)=>(b.type==='Lab')-(a.type==='Lab')||b.facultyIds.length-a.facultyIds.length);const placed=[];const settings=state.settings.scheduler||{};const score=c=>{let z=0;const prefs=state.prefs.filter(p=>p.faculty_id===c.faculty_id&&p.day===c.day);z+=prefs.filter(p=>p.kind==='preferred'&&c.start_slot<=p.slot&&p.slot<c.start_slot+c.duration_slots).length*100;z-=c.start_slot*0.5;z-=rowsForEntries().filter(e=>e.faculty_id===c.faculty_id&&e.day===c.day).length*2;return z};
 for(const j of jobs){let best=null;for(const fid of j.facultyIds){for(const d of DAYS)for(let s=0;s<=SLOTS.length-j.duration;s++){const resources=j.type==='Lab'?state.labs.filter(x=>x.active):state.rooms.filter(x=>x.active);for(const r of resources){const c={version_id:currentVersion.id,course_id:j.course.id,faculty_id:fid,section_id:j.section.id,day:d,start_slot:s,duration_slots:j.duration,session_type:j.type,room_id:j.type==='Theory'?r.id:null,lab_id:j.type==='Lab'?r.id:null};if(hardIssues(c,base.concat(placed)).length)continue;const sc=score(c);if(!best||sc>best.score)best={c,score:sc}}}}if(best)placed.push(best.c);else (state.unscheduled??=[]).push({course:j.course,section:j.section,reason:'No valid common teacher, section and resource window.'})}
 if(!placed.length)return alert('No sessions could be generated. Check eligible teachers, sections and preferences.');await sb.from('timetable_entries').delete().eq('version_id',currentVersion.id).eq('locked',false);const {error}=await sb.from('timetable_entries').insert(placed);if(error)return alert(error.message);await audit('auto_generate','timetable_version',currentVersion.id,null,{scheduled:placed.length,unscheduled:state.unscheduled?.length||0});await load();renderAll();alert(`Generated ${placed.length} validated sessions. Unscheduled: ${state.unscheduled?.length||0}.`)}
async function addFaculty(){if(role()!=='admin'&&role()!=='committee')return alert('Admin or committee permission required.');const n=prompt('Faculty name');if(!n)return;const type=prompt('Faculty type','DSCS');const ch=+prompt('Allocated credit hours','0');const {error}=await sb.from('faculty').insert({name:n,faculty_type:type||'DSCS',allocated_credit_hours:ch,max_weekly_slots:20});if(error)alert(error.message);else{await audit('create','faculty',null,{name:n});await load();renderAll()}}
async function addCourse(){if(role()!=='admin'&&role()!=='committee')return alert('Admin or committee permission required.');const code=prompt('Course code');const title=prompt('Course title');if(!code||!title)return;const p=state.programs[0],s=state.semesters.find(x=>x.program_id===p?.id);const {data,error}=await sb.from('courses').insert({course_code:code,course_title:title,program_id:p?.id,semester_id:s?.id,credit_hours:+prompt('Credit hours','3'),theory_hours:+prompt('Theory hours','3'),lab_hours:+prompt('Lab hours','0'),theory_duration_slots:+prompt('Theory session duration slots','1')}).select().single();if(error)alert(error.message);else{await audit('create','course',data.id,null,data);await load();renderAll()}}
async function addSection(){const p=state.programs.find(x=>x.name===prompt('Program','BS Computer Science'));if(!p)return;const s=state.semesters.find(x=>x.program_id===p.id&&x.name===prompt('Semester','I'));const n=prompt('Section name');if(!s||!n)return;const {error}=await sb.from('sections').insert({program_id:p.id,semester_id:s.id,name:n});if(error)alert(error.message);else{await load();renderAll()}}
async function addResource(){const kind=prompt('Type: Room or Lab','Room');const n=prompt('Name');if(!n)return;const cap=+prompt('Capacity','30');const table=/lab/i.test(kind)?'labs':'rooms';const {error}=await sb.from(table).insert({name:n,capacity:cap});if(error)alert(error.message);else{await load();renderAll()}}
window.editFaculty=async id=>{const f=state.faculty.find(x=>x.id===id);const n=prompt('Faculty name',f.name);if(!n)return;const ch=+prompt('Allocated credit hours',f.allocated_credit_hours);const {error}=await sb.from('faculty').update({name:n,allocated_credit_hours:ch}).eq('id',id);if(error)alert(error.message);else{await audit('update','faculty',id,f,{...f,name:n,allocated_credit_hours:ch});await load();renderAll()}}
window.editCourse=async id=>{const c=state.courses.find(x=>x.id===id);const title=prompt('Course title',c.course_title);if(!title)return;const {error}=await sb.from('courses').update({course_title:title}).eq('id',id);if(error)alert(error.message);else{await audit('update','course',id,c,{...c,course_title:title});await load();renderAll()}}
window.del=async(table,id)=>{if(role()!=='admin'&&role()!=='committee')return alert('Permission required.');if(!confirm('Delete this record?'))return;const {error}=await sb.from(table).delete().eq('id',id);if(error)alert(error.message);else{await audit('delete',table,id);await load();renderAll()}}
window.setPref=async(fid,day,slot)=>{const old=state.prefs.find(p=>p.faculty_id===fid&&p.day===day&&+p.slot===slot);const next=old?.kind==='available'?'preferred':old?.kind==='preferred'?'unavailable':'available';if(old)await sb.from('faculty_preferences').update({kind:next}).eq('id',old.id);else await sb.from('faculty_preferences').insert({faculty_id:fid,day,slot,kind:next});await audit('set_preference','faculty_preference',old?.id,null,{faculty_id:fid,day,slot,kind:next});await load();renderPrefsGrid()}
window.toggleLock=async id=>{const e=state.entries.find(x=>x.id===id);if(currentVersion.locked)return alert('Version is locked.');const {error}=await sb.from('timetable_entries').update({locked:!e.locked}).eq('id',id);if(error)alert(error.message);else{await audit('lock_change','timetable_entry',id,e,{locked:!e.locked});await load();renderAll()}}
window.delEntry=async id=>{const e=state.entries.find(x=>x.id===id);if(e?.locked||currentVersion.locked)return alert('Locked entry cannot be deleted.');if(!confirm('Delete timetable entry?'))return;const {error}=await sb.from('timetable_entries').delete().eq('id',id);if(error)alert(error.message);else{await audit('delete','timetable_entry',id,e);await load();renderAll()}}
async function newVersion(){const n=prompt('Version name','Draft '+(state.versions.length+1));if(!n)return;const {data,error}=await sb.from('timetable_versions').insert({name:n,academic_session:$('#academicSession').value||'2026-27',created_by:user.id}).select().single();if(error)alert(error.message);else{await audit('create','timetable_version',data.id,null,data);await load();currentVersion=data;renderAll()}}
async function saveSettings(){const scheduler={max_consecutive_theory:+$('#maxConsecutive').value,max_classes_per_day:+$('#maxDaily').value,prefer_same_room:$('#sameRoom').checked,allow_overload:$('#allowOverload').checked};await sb.from('system_settings').upsert({key:'scheduler',value:scheduler});if(currentVersion)await sb.from('timetable_versions').update({academic_session:$('#academicSession').value}).eq('id',currentVersion.id);await audit('update','system_settings',null,null,scheduler);await load();renderAll();alert('Settings saved.')}
function csvParse(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);out.push(row);row=[];cell='';continue}cell+=c}if(cell||row.length){row.push(cell);out.push(row)}return out.filter(r=>r.some(x=>x.trim()))}
async function importCSV(file){const rows=csvParse(await file.text());const h=rows.shift().map(x=>x.trim().toLowerCase());const required=['course_code','course_title','program','semester','credit_hours','theory_hours','lab_hours','teacher'];const missing=required.filter(x=>!h.includes(x));if(missing.length)return alert('Missing columns: '+missing.join(', '));const preview=rows.slice(0,8).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]?.trim()||''])));if(!confirm(`Import ${rows.length} course row(s)? Preview:\n${JSON.stringify(preview,null,2)}`))return;let ok=0;for(const r of rows){const o=Object.fromEntries(h.map((x,i)=>[x,r[i]?.trim()||'']));if(!o.course_code||!o.course_title||!o.program||!o.semester)continue;const p=state.programs.find(x=>x.name.toLowerCase()===o.program.toLowerCase());const s=state.semesters.find(x=>x.program_id===p?.id&&x.name.toLowerCase()===o.semester.toLowerCase());if(!p||!s||state.courses.some(c=>c.course_code===o.course_code))continue;const {data:c,error}=await sb.from('courses').insert({course_code:o.course_code,course_title:o.course_title,program_id:p.id,semester_id:s.id,credit_hours:+o.credit_hours,theory_hours:+o.theory_hours,lab_hours:+o.lab_hours,theory_duration_slots:1}).select().single();if(error||!c)continue;const t=state.faculty.find(x=>x.name.toLowerCase()===o.teacher.toLowerCase());if(t)await sb.from('course_teacher_assignments').insert({course_id:c.id,faculty_id:t.id});ok++}await audit('csv_import','courses',null,null,{rows:rows.length,imported:ok});await load();renderAll();alert(`Imported ${ok} of ${rows.length} row(s).`)}
function exportCSV(){const es=rowsForEntries();const head=['day','start_time','duration_slots','course_code','course_title','teacher','program','semester','section','resource','type'];const data=[head,...es.map(e=>{const c=state.courses.find(x=>x.id===e.course_id),s=state.sections.find(x=>x.id===e.section_id),p=state.programs.find(x=>x.id===s?.program_id),se=state.semesters.find(x=>x.id===s?.semester_id);return [e.day,SLOTS[e.start_slot][0],e.duration_slots,c?.course_code,c?.course_title,name('faculty',e.faculty_id),p?.name,se?.name,s?.name,e.room_id?name('rooms',e.room_id):name('labs',e.lab_id),e.session_type]} )];const csv=data.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');download('uvas-timetable.csv',csv,'text/csv')}
function download(n,d,t){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([d],{type:t}));a.download=n;a.click();URL.revokeObjectURL(a.href)}
function printView(mode){const es=rowsForEntries();let groups=[];if(mode==='complete')groups=[['Complete Timetable',es]];else if(mode==='class')groups=state.sections.map(s=>[`${s.name} · ${state.semesters.find(x=>x.id===s.semester_id)?.name||''}`,es.filter(e=>e.section_id===s.id)]);else if(mode==='semester')groups=state.semesters.map(s=>[`${state.programs.find(p=>p.id===s.program_id)?.name||''} · Semester ${s.name}`,es.filter(e=>e.section_id&&state.sections.find(x=>x.id===e.section_id)?.semester_id===s.id)]);else if(mode==='teacher')groups=state.faculty.map(f=>[f.name,es.filter(e=>e.faculty_id===f.id)]);else if(mode==='day')groups=DAYS.map(d=>[d,es.filter(e=>e.day===d)]);else if(mode==='room')groups=state.rooms.map(r=>[r.name,es.filter(e=>e.room_id===r.id)]);else groups=state.labs.map(r=>[r.name,es.filter(e=>e.lab_id===r.id)]);const html=groups.filter(g=>g[1].length||mode==='complete').map(g=>`<section><h2>${esc(g[0])}</h2><table><tr><th>Day</th><th>Time</th><th>Course</th><th>Teacher</th><th>Section</th><th>Room/Lab</th><th>Type</th></tr>${g[1].sort((a,b)=>DAYS.indexOf(a.day)-DAYS.indexOf(b.day)||a.start_slot-b.start_slot).map(e=>`<tr><td>${e.day}</td><td>${time(e.start_slot)}${e.duration_slots>1?' · '+e.duration_slots+' slots':''}</td><td>${esc(name('courses',e.course_id))}</td><td>${esc(name('faculty',e.faculty_id))}</td><td>${esc(name('sections',e.section_id))}</td><td>${esc(e.room_id?name('rooms',e.room_id):name('labs',e.lab_id))}</td><td>${e.session_type}</td></tr>`).join('')}</table></section>`).join('');const w=open('','_blank');w.document.write(`<html><head><title>UVAS Timetable</title><style>@page{size:A4 landscape;margin:10mm}body{font:12px Arial;color:#111}h1{text-align:center;margin:0}h2{margin-top:20px;border-bottom:1px solid #333;padding-bottom:4px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #333;padding:5px;text-align:left}th{background:#eee}.footer{margin-top:30px;display:flex;justify-content:space-between}section{page-break-inside:avoid}</style></head><body><h1>University of Veterinary & Animal Sciences</h1><h1>Ravi Campus, Pattoki</h1><h1>Department of Statistics and Computer Science</h1><p style="text-align:center">${esc(currentVersion?.academic_session||'')}</p>${html}<div class="footer"><span>Signature of Time Table Committee Member</span><span>Signature of Chairperson</span><span>Signature of DSA</span><span>Signature of Concerned Dean</span></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
async function ai(e){e.preventDefault();const p=$('#aiPrompt').value.trim();if(!p)return;$('#aiResult').textContent='Interpreting command…';try{const r=await fetch('/.netlify/functions/gemini',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p,data:{faculty:state.faculty,programs:state.programs,semesters:state.semesters,sections:state.sections,courses:state.courses,entries:rowsForEntries()}})});const j=await r.json();const a=j.action;if(!a){$('#aiResult').textContent=j.error||'No structured action returned.';return}$('#aiResult').textContent=JSON.stringify(a,null,2);if(a.type==='generate_timetable'){if(confirm('Generate a new conflict-free timetable?'))await generate();return}if(a.type==='schedule_course'){const c=state.courses.find(x=>x.course_code===a.course_code||x.course_title.toLowerCase()===String(a.course||'').toLowerCase());const f=state.faculty.find(x=>x.name.toLowerCase()===String(a.teacher||'').toLowerCase());const s=state.sections.find(x=>x.name.toLowerCase()===String(a.section||'').toLowerCase());const d=a.day;const st=SLOTS.findIndex(x=>x[0]===a.start_time);if(!c||!f||!s||st<0){$('#aiResult').textContent+='\nCould not resolve course/teacher/section/time.';return}const type=a.session_type||'Theory',dur=type==='Lab'?3:+a.duration_slots||1;const rooms=state.rooms.find(x=>x.name.toLowerCase()===String(a.resource||'').toLowerCase()),labs=state.labs.find(x=>x.name.toLowerCase()===String(a.resource||'').toLowerCase());const candidate={version_id:currentVersion.id,course_id:c.id,faculty_id:f.id,section_id:s.id,day:d,start_slot:st,duration_slots:dur,session_type:type,room_id:type==='Theory'?rooms?.id:null,lab_id:type==='Lab'?labs?.id:null};if(!hardIssues(candidate).length&&confirm('AI proposed a valid action. Apply it?')){const {error}=await sb.from('timetable_entries').insert(candidate);if(error)alert(error.message);else{await audit('ai_schedule','timetable_entry',null,null,candidate);await load();renderAll();}}else $('#aiResult').textContent+='\nAction rejected by deterministic validation or cancelled.';return}$('#aiResult').textContent+='\nThis command was interpreted but no automatic mutation was authorized.'}catch(err){$('#aiResult').textContent=err.message}}
init();